import React from 'react';

const Duke890RSuspension: React.FC = () => {
    return (
        <article className="prose lg:prose-xl">
            <h2>Dialing in the Duke: A Track Day DOE</h2>
            <p className="lead">
                How we used Design of Experiments to maximize rear grip on a KTM Duke 890R and shave seconds off lap times.
            </p>

            <h3>The Challenge: Taming the Beast on Corner Exit</h3>
            <p>
                The KTM Duke 890R is a weapon on the track. It's light, powerful, and incredibly agile. However, one of our track day enthusiasts, Alex, was struggling with a specific issue: inconsistent rear grip on corner exit. The bike would either spin up the rear tire or squat too much, running wide and killing his drive onto the straights. He'd tried fiddling with the suspension settings, but it felt like guesswork. He was changing one thing at a time, but the adjustments seemed to interact in unpredictable ways.
            </p>

            <h3>Enter Design of Experiments (DOE)</h3>
            <p>
                Instead of random tweaking, we decided to take a more structured approach using this very DOE calculator. The goal was to systematically test different combinations of suspension settings to find the optimal setup for maximizing rear grip.
            </p>

            <h4>Step 1: Defining Factors and Levels</h4>
            <p>
                We identified four key factors that we believed would have the most significant impact on rear grip. For each factor, we chose a "high" and a "low" setting based on the manufacturer's recommendations and Alex's own experience.
            </p>
            <ul>
                <li><strong>Tire Pressure (Rear):</strong> Low (30 psi), High (34 psi)</li>
                <li><strong>Low-Speed Compression Damping:</strong> Low (8 clicks out), High (12 clicks out)</li>
                <li><strong>Low-Speed Rebound Damping:</strong> Low (7 clicks out), High (11 clicks out)</li>
                <li><strong>Spring Preload:</strong> Low (Position 4), High (Position 6)</li>
            </ul>

            <h4>Step 2: Designing the Experiment</h4>
            <p>
                With four factors at two levels each, a full factorial experiment would require 2<sup>4</sup> = 16 runs. Using the DOE calculator, we generated a randomized experimental plan. For each run, Alex would do a 3-lap stint, focusing on a specific corner exit where the grip issue was most pronounced.
            </p>

            <h4>Step 3: Measuring the Response (Y)</h4>
            <p>
                The Y-variable we were trying to maximize was "Rear Wheel Grip". This is subjective, so we needed a way to quantify it. Alex rated the grip on a scale of 1 to 10 after each run, where 1 was "like riding on ice" and 10 was "glued to the track". While subjective, a consistent rider can provide surprisingly reliable data.
            </p>

            <h3>The Results: From Confusion to Clarity</h3>
            <p>
                After completing the 16 runs and inputting the grip ratings into the calculator, the analysis tools gave us a wealth of information.
            </p>

            <p>The Pareto chart of effects immediately showed us what mattered most:</p>
            <ol>
                <li><strong>Tire Pressure:</strong> This had the largest effect by a significant margin. Lower pressure was consistently better.</li>
                <li><strong>Rebound Damping:</strong> This had the second-largest effect. A faster rebound (fewer clicks out) was helping the tire stay in contact with the pavement.</li>
                <li><strong>Interaction: Pressure * Rebound:</strong> The analysis also flagged a significant interaction effect. The effect of tire pressure was even more pronounced when combined with the right rebound setting. The calculator's interaction plot made this easy to visualize.</li>
                <li><strong>Compression & Preload:</strong> These had a much smaller effect in comparison. We could set these to a neutral baseline and focus on the big hitters.</li>
            </ol>

            <p>The regression formula generated by the tool gave us a predictive model:</p>
            <pre><code>Grip = 7.5 - 1.5 * (Tire Pressure) + 0.8 * (Rebound) + ... </code></pre>
            <p>
                This model allowed us to predict the grip for settings we hadn't even tested, helping us zero in on the absolute best setup.
            </p>

            <h3>Conclusion: Data-Driven Decisions Win Races</h3>
            <p>
                By using a DOE approach, we moved from frustrating guesswork to a clear, data-driven setup. The optimal settings we found were not something Alex would have likely stumbled upon by adjusting one factor at a time due to the strong interaction effect.
            </p>
            <p>
                The result? A much more confident rider, a bike that was easier and faster to ride, and a 1.5-second drop in Alex's average lap time. This is a perfect example of how applying a bit of statistical rigor can yield huge dividends in the real world, even in a field as "feel-based" as motorcycle racing.
            </p>
        </article>
    );
};

export default Duke890RSuspension;
